# Generated by Django 5.2.8 on 2025-12-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name_plural': 'Project statuses'},
        ),
    ]
