# Generated by Django 5.2.8 on 2026-01-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_color',
            field=models.CharField(default='#787878', max_length=7),
        ),
    ]
