# Generated by Django 5.2.8 on 2026-04-03 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_code_project_is_code_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
