# Generated by Django 5.2.8 on 2026-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
