# Generated by Django 5.2.8 on 2026-04-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_servicetype_project_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='entity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
