# Generated by Django 5.2.8 on 2026-04-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
