# Generated by Django 5.2.8 on 2026-04-21 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_project_project_type_delete_projecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agreement_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
