# Generated by Django 5.2.8 on 2026-04-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_agreement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agreement_date',
            field=models.DateField(),
        ),
    ]
