# Generated by Django 5.2.8 on 2026-05-26 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_grade_short_name'),
        ('projects', '0018_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country_of_ubo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubo_projects', to='accounts.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.country'),
        ),
    ]
