# Generated by Django 5.2.8 on 2026-06-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_country_of_ubo_alter_project_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='country_of_ubo',
        ),
    ]
