# Generated by Django 5.2.8 on 2026-06-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_project_country_of_ubo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
