# Generated by Django 5.2.8 on 2026-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_servicetype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
