# Generated by Django 5.2.8 on 2026-09-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_task_is_active_tasktype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
