# Generated by Django 5.2.8 on 2025-12-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_grade_role_user_date_left_detailedgrade_user_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.grade'),
        ),
    ]
