# Generated by Django 5.2.8 on 2025-12-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_detailedgrade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='detailed_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.detailedgrade'),
        ),
        migrations.AlterField(
            model_name='detailedgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_grades', to='accounts.grade'),
        ),
    ]
