# Generated by Django 5.2.8 on 2025-12-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_position_remove_user_detailed_grade_grade_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='accounts.position'),
        ),
    ]
