# Generated by Django 5.2.8 on 2026-04-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_department_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='country',
        ),
    ]
