# Generated by Django 5.2.8 on 2026-04-24 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='short_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
