# Generated by Django 5.2.8 on 2026-06-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userstatus_user_status_userstatushistory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userstatushistory',
            constraint=models.UniqueConstraint(fields=('user', 'status', 'started_at'), name='unique_user_status_date'),
        ),
    ]
