# Generated by Django 5.2.8 on 2026-06-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userstatushistory_unique_user_status_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name_plural': 'User statuses'},
        ),
        migrations.AlterModelOptions(
            name='userstatushistory',
            options={'ordering': ['started_at'], 'verbose_name_plural': 'User status history'},
        ),
    ]
