# Generated by Django 5.2.8 on 2026-06-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_usergradehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergradehistory',
            options={'ordering': ['started_at'], 'verbose_name_plural': 'User grade history'},
        ),
        migrations.AddField(
            model_name='usergradehistory',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.position'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='usergradehistory',
            constraint=models.UniqueConstraint(fields=('user', 'position', 'grade', 'started_at'), name='unique_user_grade_date'),
        ),
    ]
