# Generated by Django 5.2.8 on 2026-01-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_grade_position'),
        ('calendars', '0001_initial'),
        ('clients', '0001_initial'),
        ('projects', '0003_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.task'),
        ),
    ]
