# Generated by Django 5.2.8 on 2026-01-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_alter_timeentry_client_alter_timeentry_country_and_more'),
        ('projects', '0003_project_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name_plural': 'Time entries'},
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.tasktype'),
        ),
    ]
