# Generated by Django 5.2.8 on 2026-01-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_alter_timeentry_options_timeentry_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='weekends_included',
            field=models.BooleanField(default=False),
        ),
    ]
