# Generated by Django 5.2.8 on 2026-02-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_activation_code'),
        ('calendars', '0005_alter_timeentry_weekends_included'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('holiday_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_working_weekend', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'year', 'month', 'day'], name='calendars_c_country_081098_idx'), models.Index(fields=['country', 'month', 'day'], name='calendars_c_country_c6d4c2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_holiday', True), ('is_working_weekend', True), _negated=True), name='not_both_holiday_and_working_weekend'), models.CheckConstraint(condition=models.Q(models.Q(('is_recurring', True), ('year__isnull', True)), ('is_recurring', False), _connector='OR'), name='recurring_has_no_year')],
            },
        ),
    ]
