# Generated by Django 5.2.8 on 2026-02-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_calendar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendar',
            name='not_both_holiday_and_working_weekend',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='is_holiday',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='is_working_weekend',
        ),
        migrations.AddField(
            model_name='calendar',
            name='day_type',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('working_weekend', 'Working weekend'), ('working_day', 'Working day')], default='working_day', max_length=32),
        ),
    ]
