# Generated by Django 5.2.8 on 2026-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_remove_calendar_not_both_holiday_and_working_weekend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='day_type',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('working_weekend', 'Working weekend'), ('working_day', 'Working day')], max_length=32),
        ),
    ]
