# Generated by Django 5.2.8 on 2026-02-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_activation_code'),
        ('calendars', '0008_alter_calendar_day_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.country'),
        ),
    ]
