# Generated by Django 5.2.8 on 2026-03-02 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0010_alter_calendar_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='start_date',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='date',
            field=models.DateField(default=datetime.date(2026, 3, 2)),
            preserve_default=False,
        ),
    ]
