# Generated by Django 5.2.8 on 2026-03-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0011_remove_timeentry_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
