# Generated by Django 5.2.8 on 2026-03-03 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0012_alter_timeentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 3, 8, 11, 46, 235801, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
