# Generated by Django 5.2.8 on 2026-03-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0013_timeentry_created_at_timeentry_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('working_days_of_week', models.JSONField(default=list, help_text='Weekday numbers (0=Mon ... 6=Sun)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
