# Generated by Django 5.2.8 on 2026-03-24 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_activation_code'),
        ('calendars', '0014_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_day', models.PositiveSmallIntegerField(default=8)),
                ('working_days', models.JSONField(default=list, help_text='Weekday numbers (0=Mon ... 6=Sun)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.country')),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
    ]
