# Generated by Django 5.2.8 on 2026-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0015_countrysettings_delete_globalsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrysettings',
            options={'verbose_name_plural': 'Country settings'},
        ),
        migrations.AlterField(
            model_name='countrysettings',
            name='working_days',
            field=models.JSONField(default=[0, 1, 2, 3, 4], help_text='Weekday numbers (0=Mon ... 6=Sun)'),
        ),
    ]
