# Generated by Django 5.2.8 on 2026-04-30 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0016_alter_countrysettings_options_and_more'),
        ('projects', '0017_remove_project_name_project_ic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='project',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='project_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectcode'),
        ),
    ]
