# Generated by Django 5.2.8 on 2026-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0017_remove_timeentry_project_timeentry_project_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='weekends_included',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='day_type',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('working_weekend', 'Working weekend')], max_length=32),
        ),
    ]
