# Generated by Django 5.2.8 on 2026-06-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0019_leavedocument_timeentry_leave_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
