# Generated by Django 5.2.8 on 2026-06-15 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0020_leavedocument_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
