# Generated by Django 5.2.8 on 2026-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0022_alter_timeentry_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='task_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task_type_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
