# Generated by Django 5.2.8 on 2026-06-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0023_timeentry_task_snapshot_timeentry_task_type_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='task_snapshot',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='task_type_snapshot',
        ),
    ]
