# Generated by Django 5.2.8 on 2026-01-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='manager',
        ),
    ]
