# Generated by Django 5.2.8 on 2026-04-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_pie_client_pie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
