# Generated by Django 5.2.8 on 2026-04-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_pie_name_alter_sector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bvd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
