# Generated by Django 5.2.8 on 2026-04-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_bvd_alter_client_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='personal_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
