# Generated by Django 5.2.8 on 2026-06-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_phone_number'),
        ('clients', '0008_alter_client_client_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country_of_ubo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubo_projects', to='accounts.country'),
        ),
    ]
